class FIFA(Base):
    __tablename__ = 'FIFA'

    ID = Column(Integer, primary_key=True)
    Name = Column(Text)
    Age = Column(Integer)
    Photo = Column(Text)
    Nationality = Column(Text)
    Flag = Column(Text)
    Overall = Column(Integer)
    Potential = Column(Integer)
    Club = Column(Text)
    Club_Logo = Column('Club Logo', Text)
    Value = Column(Text)
    Wage = Column(Text)
    Special = Column(Text)
    Preferred_Foot = Column('Preferred Foot', Text)
    International_Reputation = Column('International Reputation', Text)
    Weak_Foot = Column('Weak Foot', Float)
    Skill_Moves = Column('Skill Moves', Float)
    Work_Rate = Column('Work Rate', Text)
    Body_Type = Column('Body Type', Text)
    Real_Face = Column('Real Face', Text)
    Position = Column(Text)
    Joined = Column(Text)
    Loaned_From = Column('Loaned From', Text)
    Contract_Valid_Until = Column('Contract Valid Until', Text)
    Height = Column(Text)
    Weight = Column(Text)
    Release_Clause = Column('Release Clause', Text)
    Kit_Number = Column('Kit Number', Text)
    Best_Overall_Rating = Column('Best Overall Rating', Text)
    COL29 = Column(Text)
    COL30 = Column(Text)

